# Generated by Django 4.0.4 on 2022-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_autor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
    ]
