# Generated by Django 4.0.4 on 2022-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_autor_email_alter_autor_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Alta de usuario'),
        ),
    ]
