# Generated by Django 4.0.4 on 2022-04-20 16:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Descripcion'),
        ),
    ]
